apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    dashboard:
      enabled: true
      domain: traefik.k3s.bartbrinkman.nl
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: traefik-k3s-bartbrinkman-nl
  namespace: kube-system
spec:
  secretName: traefik-k3s-bartbrinkman-nl-tls
  issuerRef:
    name: letsencrypt-staging-secret
    kind: ClusterIssuer
  commonName: traefik.k3s.bartbrinkman.nl
  dnsNames:
  - traefik.k3s.bartbrinkman.nl
  